### ISSUE TITLE
Make project easy to setup

### ISSUE THREAD

**Issue by GantMan** [GantMan/nsfw_model#1]
Setup a:
* pip requirement or conda env file
* a script to perform inference on one image

Derive onboarding help from something popular like https://github.com/yahoo/open_nsfw for example

**Comment by bedapudi6788** [comment]
@GantMan , I created a pull request with code for easily running predictions with Keras. I can also add a requirements.txt and setup.py to push to pypi if you want to.

**Comment by GantMan** [comment]
I love it!  Yes, please contribute the others as well!  I'll merge the existing PR and hope to see a second one soon.

**Comment by bedapudi6788** [comment]
@GantMan sure, that's great. I will add the setup.py to make this pip installable.

**Comment by bedapudi6788** [comment]
Hi @GantMan , I am currently adding the setup.py and reorganising this into training and prediction folders. For pushing to PyPi, which name do you want to use.

**Comment by GantMan** [comment]
Great work!  

I've been researching ML for a while now, and programming for 20 years, but I'm sad to say I've never gotten this far in Python till this project 😆   (I was a Ruby/JS dev)

Should I figure out PyPi and publish there with everything you've setup?

**Comment by bedapudi6788** [comment]
@GantMan that's great. As a deep learning enthusiast this project interests me very much. Please create a account in https://pypi.org/ and update your name and email in setup.py. Then you will be able to upload the project by running python setup.py upload.

**Comment by bedapudi6788** [comment]
@GantMan Also, will it be possible for you to share the  current version of cleaned dataset, so that I can try and experiment with different model architectures.

**Comment by GantMan** [comment]
I'll have a new model and a torrent of the dataset soon.

**Comment by GantMan** [comment]
@bedapudi6788 - can you let me know if this works?

[NSFW_March_2019.7z.torrent.zip](https://github.com/GantMan/nsfw_model/files/2931759/NSFW_March_2019.7z.torrent.zip)

**Comment by bedapudi6788** [comment]
@GantMan Thank you. Although I downloaded similar data using ripme.jar (~310GB), your validation data set would be useful for comparisons.

**Comment by GantMan** [comment]
That torrent has deduplicated pretty clean data.  I hope it's of use!

**Comment by bedapudi6788** [comment]
@GantMan It will be very helpful in my experiments. I am unable to download the dataset using the torrent. Can you please let me know when you start seed. Thank you.

**Comment by bedapudi6788** [comment]
@GantMan This will of course be very helpful. Can you please let me know once you start seeding. Right now, there are no peers available. Once I download this torrent, I will be able to re-share the data by uploading it on my personal server.

**Comment by GantMan** [comment]
For future reference:
Ask me or https://twitter.com/KarthikRevanuru for the key

https://mega.nz/#!Q5RnDQYa

**Comment by xiexiaoshinick** [comment]
Hello, brother, I am from Beijing, China. I want to download the dataset you shared through the torrent, but it failed. We can't use Twitter here. There is no way to know the password of MEGA. Can you help me?

**Comment by xiexiaoshinick** [comment]
@GantMan Hello, brother, I am from Beijing, China. I want to download the dataset you shared through the torrent, but it failed. We can't use Twitter here. There is no way to know the password of MEGA. Can you help me?

**Comment by GantMan** [comment]
Hello in China!   Do you have access to [Imgur](https://imgur.com/a/iWQs2kK)?

**Comment by luyenthithongminh** [comment]
@GantMan I tried to use the provided key from https://imgur.com/a/iWQs2kK however the key doesn't seem to work, could you provide a valid key please, really appreciate your help!

**Comment by GantMan** [comment]
see this thread:  https://github.com/GantMan/nsfw_model/issues/11#issuecomment-485054701

**Comment by GantMan** [comment]
I'll close this ticket.

**Comment by luyenthithongminh** [comment]
Thanks !

**Comment by Vozf** [comment]
So what's up with pypi?
