### ISSUE TITLE
Netflix's homepage is tagged as Hentai but porn sites aren't

### ISSUE THREAD

**Issue by SkyfallWasTaken** [GantMan/nsfw_model#105]
The model flags [the netflix homepage](https://cdn.discordapp.com/attachments/960135532107681792/961310740768235580/screenshot.jpg?size=4096) image as NSFW (`{"hentai":71,"drawing":23,"porn":3,"neutral":1,"sexy":0}`) but flags Pornhub's homepage as SFW and a drawing (`{"drawing":64,"hentai":25,"neutral":8,"porn":1,"sexy":0}`)

**Comment by GantMan** [comment]
That's strange!  however, I've done a test with NSFWJS on two advanced models an they both got it right


![image](https://user-images.githubusercontent.com/997157/162059521-55a92a03-2536-4abc-b6ab-d48e89c981d2.png)
![image](https://user-images.githubusercontent.com/997157/162059878-88b5aab3-e4ed-46a8-898c-2e80611809f8.png)


When you mention Pornhub's homepage, what resolution?

There will def be false positives, but please supply links when you find issues.  I'm building a larger dataset to fix any false-positives in the future.

**Comment by SkyfallWasTaken** [comment]
Hey, thanks for the reply!

**Comment by GantMan** [comment]
So I think the problem  is that it's the entire webpage at once.  And when you size that screenshot down to 224x224 (the dimensions that the AI reads) it's too small to see NSFW content at high confidence.

**Comment by colindean** [comment]
I think the last comment explains the problem here, so closing.
