### ISSUE TITLE
Error while predicting using the model

### ISSUE THREAD

**Issue by StarkGang** [GantMan/nsfw_model#107]
Hey, I have been trying your model for a while, but I am getting this error:
```ValueError: Unexpected result of `predict_function` (Empty batch_outputs). Please use `Model.compile(..., run_eagerly=True)`, or `tf.config.run_functions_eagerly(True)` for more information of where went wrong, or file a issue/bug to `tf.keras`.```

It's telling me to compile the model, why is it so? 

I tried the both method, but looks like it didn't help. Any solution?

**Comment by StarkGang** [comment]
This issue has been resolved. Thank you :)

**Comment by R1senDev** [comment]
@StarkGang
Tell me, please, how did you solve it?
