### ISSUE TITLE
Different licenses are used in pypi and the repository

### ISSUE THREAD

**Issue by kyoto7250** [GantMan/nsfw_model#112]
Hello, Thank you for your awesome work!

The license of the repository seems to be MIT, but the license at pypi is GPLv3.

Is there a reason for this?
And which license do we need to follow for actual use?

Best regards.

ref:

license:
https://github.com/GantMan/nsfw_model/blob/master/LICENSE.md

pypi:
https://pypi.org/project/nsfw-detector/#description

Issue:
https://github.com/GantMan/nsfw_model/issues/43

**Comment by GantMan** [comment]
that was a small mistake.  The license is MIT

**Comment by kyoto7250** [comment]
@GantMan 

Thanks for the quick reply!
I will close this issue.
