### ISSUE TITLE
Inception Model Access Denied for download

### ISSUE THREAD

**Issue by colestiegler** [GantMan/nsfw_model#115]
When I try to access the Inception models, I get an "Access Denied" message, specifically:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId><the request id></RequestId>
<HostId><the host ID></HostId>
</Error>
```

I would like to compare the performance of the inception model to the newer mobilenet model, is there a way you can make this available again?

**Comment by benmussi** [comment]
Seems you can download the model from the NSFWJS website:

https://nsfwjs.com/model/model.json
https://nsfwjs.com/model/group1-shard1of6
https://nsfwjs.com/model/group1-shard2of6
https://nsfwjs.com/model/group1-shard3of6
https://nsfwjs.com/model/group1-shard4of6
https://nsfwjs.com/model/group1-shard5of6
https://nsfwjs.com/model/group1-shard6of6

**Comment by colindean** [comment]
All URLs in the README are currently operational and valid. Please reopen if something is not working for you across multiple Internet connections.
