### ISSUE TITLE
How to create own model?

### ISSUE THREAD

**Issue by DankMemeGuy** [GantMan/nsfw_model#117]
I use a variation of NSFWJS with this model, but I would like to start developing my own model. I read the README file, but I'm still not sure how to go about this.

Can you create a basic step by step guide on how to create a model, or YouTube video? I have the images that are categorized, just not sure how to actually go about training a model. Can you maybe show how images have to laid out, then the steps to run the images through a model etc?

Thank you!

**Comment by DankMemeGuy** [comment]
@GantMan what are your rates, or what would you charge to be able to work with me to improve the model? I have tried for almost two months and I cannot figure out how to build a new model, or train a revised version of Inception V3.

I have a dataset, I just don't get what steps to do, one by one, to get the job done (even with your amazing documents and articles). Can I pay you to help me through this? I would really love to learn how to do this as I know this is the future of coding!

**Comment by GantMan** [comment]
Hey Dank!  What profession are you looking to get into?  I can point you in the right direction and the right tools to get you started.  I made this model 3 years ago, and I feel there are more advanced techniques now, and it wouldn't be too hard to beat my results.

**Comment by DankMemeGuy** [comment]
> Hey Dank! What profession are you looking to get into? I can point you in the right direction and the right tools to get you started. I made this model 3 years ago, and I feel there are more advanced techniques now, and it wouldn't be too hard to beat my results.

Thank you for the quick response! I am still in university but I'm trying to do side projects just to learn how to build web apps. nothing fancy or anything, but just small things to learn how things work etc to build my skillset in being able to build the web apps, or software that connects to web services, etc.

I know with how fast AI is developing, 3 years is like an eternity, but from all the Googling I've been doing, your GitHub has really been the most helpful in terms of me learning. Or maybe I am Googling wrong, any resources you can point me towards allowing me to build a stronger model?

Anything would honestly be very helpful, I have spent more time trying to figure this out then I will admit lol. I know more Python, but I know JS is really where a lot of web app development is happening so I have ben trying to get more into JS too.

**Comment by GantMan** [comment]
One thing I can definitely recommend is [my book](https://www.amazon.com/Learning-TensorFlow-js-Powerful-Machine-JavaScript/dp/1492090794/ref=sr_1_1?crid=MB3GNAU63ULL&keywords=learning+tensorflow.js&qid=1671654859&sprefix=learning+tensorflow.js%2Caps%2C105&sr=8-1) .

There are tons of options out there, but once you know a bit more, I suggest you take on a personal project!
