### ISSUE TITLE
Neutral dataset?

### ISSUE THREAD

**Issue by DankMemeGuy** [GantMan/nsfw_model#119]
Just wondering what was the source for the Neutral class?

I noticed that https://github.com/alex000kim/nsfw_data_scraper and https://github.com/EBazarov/nsfw_data_source_urls don't have a Neutral dataset, so what did you use for that training? Do you have a list of subreddits you scraped, or any other sources you used?

Just trying to get a sense of what was used so I don't end up training the model on a classification with images it was already trained on, as much as I can. Also would be helpful building a new dataset for that class since it's been 5 years since training so perhaps those sources have new images to use.

Thank you @GantMan, much appreciated all the work you put into this!

**Comment by DankMemeGuy** [comment]
Nevermind, it's there. I just clearly haven't had enough coffee yet haha. https://github.com/alex000kim/nsfw_data_scraper/blob/main/scripts/source_urls/neutral.txt

**Comment by GantMan** [comment]
Totally ok!  I need a second cup myself!
