### ISSUE TITLE
Why is keras training slow?

### ISSUE THREAD

**Issue by chenzi** [GantMan/nsfw_model#13]
I use aws ec2 p2.xlarge server 12G gpu 60G Memory， But training is still slow.

![WX20190404-155500](https://user-images.githubusercontent.com/5486633/55538918-153e7580-56f2-11e9-9431-168ae55c89d0.png)

![image](https://user-images.githubusercontent.com/5486633/55539071-66e70000-56f2-11e9-87a4-bf1a7c4ad947.png)

**Comment by chenzi** [comment]
I get an error RuntimeWarning: Can save best model only with val_acc available, skipping.
  'skipping.' % (self.monitor), RuntimeWarning)
![image](https://user-images.githubusercontent.com/5486633/55541331-63a24300-56f7-11e9-9fd9-3efac767322f.png)

**Comment by GantMan** [comment]
You're having around the same speed I have.

I think training is slower in this Keras model for 2 reasons.   There is real-time image manipulation to augment the training set, and the amount of data per epoch is huge.  Given the batch size, I'm using.  
To get this model to 93% I trained on my machine for days.

As for your error message:
Did you change anything in the code?  If so consult this link https://github.com/keras-team/keras/issues/836

**Comment by GantMan** [comment]
Another thing, since your computer you're using has more power than mine, you might want to try removing my `workers=0` line.  You might get a training boost.

**Comment by chenzi** [comment]
I tryed set wokrder=1000 then The training speed is faster.
