### ISSUE TITLE
Drop Pythons older than 3.7, explicitly support up to 3.11

### ISSUE THREAD

**Issue by colindean** [GantMan/nsfw_model#130]
This should be 3.7:

https://github.com/GantMan/nsfw_model/blob/80bc87dfe44f900fb74ca71e773c8ed66c86f231/setup.py#L20

This should drop 3.6 and add 3.7…3.11:

https://github.com/GantMan/nsfw_model/blob/80bc87dfe44f900fb74ca71e773c8ed66c86f231/setup.py#L126-L127

…but we also need some tests in CI to validate use on newer Pythons.

**Comment by colindean** [comment]
Actually, should consider dropping Python 3.7, too, because it's EOL in a few months and Python 3.8 is the oldest that tensorflow-macos supports.

**Comment by Vanphongle** [comment]
Hi Colin, I just created a pull request. Please review the changes.
