### ISSUE TITLE
Model Weight License

### ISSUE THREAD

**Issue by shiv203** [GantMan/nsfw_model#142]
The repo is currently shared under mit license. There are also some trained model weights shared in this repo. it would be kind of you to clarify if the weights also comes under the same license.

Thanks

**Comment by GantMan** [comment]
everything in the repo is under MIT.  I'm happy to adjust the license if MIT is too restrictive.

**Comment by shiv203** [comment]
Thanks for clarifying that the model is also under the MIT license. Mit license is good.

Thanks.
