### ISSUE TITLE
i can not pip install on mac m1 chip, with Python 3.9.18

### ISSUE THREAD

**Issue by kingrmb** [GantMan/nsfw_model#159]
i can not pip install on mac m1 chip, with Python 3.9.18, tensorflow.__version__==2.16.1
tensorboard                  2.16.2
tensorboard-data-server      0.7.2
tensorflow                   2.16.1
tensorflow-hub               0.12.0
tensorflow-io-gcs-filesystem 0.36.0
tensorflow-macos             2.16.1

anyone can tell me which version should be

with this error:
AttributeError: module 'tensorflow._api.v2.compat.v1' has no attribute 'estimator'

**Comment by sinogrime** [comment]
thanks for telling us how you solved your problem

**Comment by kingrmb** [comment]
finally, i give up~ and find another lib

phil ming ***@***.***> 于2024年9月1日周日 23:36写道：

**Comment by fusionconsulting** [comment]
What was the other lib? I'm having the same issue.
