### ISSUE TITLE
Error: Running model failed: Not found: FetchOutputs node dense_3: not found

### ISSUE THREAD

**Issue by Max1880** [GantMan/nsfw_model#16]

**Comment by Max1880** [comment]
I run your model with https://github.com/reneweb/react-native-tensorflow. I got this error message "Error: Running model failed: Not found: FetchOutputs node dense_3: not found". Could you help me?

**Comment by GantMan** [comment]
Sure.  Is your code open source?   If not I have a react-native-tensorflow example codebase I could use, but I figured it would be best to directly use the source you're using.

**Comment by Max1880** [comment]
I solved this issue. I found the output layer with this tool https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/graph_transforms#inspecting-graphs.
