### ISSUE TITLE
Convert model for TensorFlow 1.1.0

### ISSUE THREAD

**Issue by Max1880** [GantMan/nsfw_model#17]
I run nsfw.299x299.pb model on react-native-tensorflow and got this message:
```
Error: Running model failed: Invalid argument: NodeDef mentions attr 'dilations' not in
Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF,
DT_FLOAT, DT_DOUBLE]; attr=strides:list(int);
attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"];
attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef:
conv2d_1/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1],
padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true,
_device="/job:localhost/replica:0/task:0/cpu:0"](_recv_input_1_0, conv2d_1/kernel/read).
(Check whether your GraphDef-interpreting binary is up to date with 
your GraphDef-generating binary.).
	 [[Node: conv2d_1/convolution = Conv2D[T=DT_FLOAT, data_format="NHWC", 
dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true,
_device="/job:localhost/replica:0/task:0/cpu:0"](_recv_input_1_0, conv2d_1/kernel/read)]]
```
1) A google search prompted me that the tensorflow version and the models do not match. Is there a way to convert a model for version 1.1.0?
2) I need to run this model on iOS and Android on JS with react-native. How can i do this?

**Comment by GantMan** [comment]
TFLite is probably fastest on devices (react-native).  But TFLite is still awaiting iOS support.  I believe they say it is coming soon.

The best way to do this (for speed) on iOS is to use `react-native-vision` library, which will use the coreML model.  But doesn't work on Android.

I'll see if I can convert the model to 1.1.0.   That will take a little research.  Let me know if you find anything first.

**Comment by Max1880** [comment]
Oh. Thank you for your attention. I will seek a solution to this problem with you. 😊

**Comment by GantMan** [comment]
It looks like if you convert the model and have Tensorflow 1.1 installed when you're converting, it should make a TF 1.1 model.

https://github.com/amir-abdi/keras_to_tensorflow

**Comment by Max1880** [comment]
Oh. This source code uses the functionality from Tensorflow 1.7.0, and I have a bad understanding of this issue. You can close this issue, because I will now run this model on the server. Thanks for the help.
