### ISSUE TITLE
Potential issue with `self_clense.py` 

### ISSUE THREAD

**Issue by alexkimxyz** [GantMan/nsfw_model#2]
I haven't looked through the `self_clense.py` script thoroughly,  but it looks like you are using the model to change the distribution of your data by moving `misclassified` instances to their, supposedly,  correct directory (class).
This process may (and most likely did) reduce one type of noise, but enhance the other.
So any potential gain in accuracy that you may have gotten from this process is only due to the feedback loop between the model and data distribution. This is not a rigorous/scientifically valid approach to "fix" noisy data.

**Comment by GantMan** [comment]
I had the same thought!  My resolution was that I'd be able to use that to clean false negatives, but the process does nothing for false positives.  This makes a somewhat asymmetric improvement between recall and precision, but I feel still improves performance on something which is dangerous for a NSFW detector, that false negatives slipping through is quite problematic.

**Comment by alexkimxyz** [comment]
Thanks for the response. I wanted to make sure that this potential issue doesn't go unnoticed. Feel free to close the issue.

**Comment by GantMan** [comment]
Always a fan of feedback!
