### ISSUE TITLE
Training with mobilenet?

### ISSUE THREAD

**Issue by onexuan** [GantMan/nsfw_model#20]
Training with mobilenet?

**Comment by GantMan** [comment]
Sure, that can be a thing.  Is this something you'd like to take on?  Or are you asking for code on how to do this?

**Comment by onexuan** [comment]
I hope you support it.

**Comment by GantMan** [comment]
Gotcha, so you're looking for a smaller/faster model.   I'll keep this ticket open, and help whoever wants to do it.  If no one, I may just take it on myself.

**Comment by onexuan** [comment]
it is glad to hear that!

**Comment by GantMan** [comment]
Currently, over 80% accurate, I'll tune it over the weekend and update you.

**Comment by onexuan** [comment]
Great work, I know you train it with Tensorflow, I wish I could train like you. I hope it support mxnet for me, I don't how to train, but i know use with mxnet  in mobile phone!

**Comment by GantMan** [comment]
90% accurate, gonna fine-tune

**Comment by onexuan** [comment]
perfect! waiting...

**Comment by GantMan** [comment]
Here:
![image](https://user-images.githubusercontent.com/997157/56872614-b5857280-69f0-11e9-86c4-27b1c5e6fe39.png)

Download Keras Model: 

I'll keep trying to get it more accurate and will update the main README.md when it's ready.
https://s3.amazonaws.com/ir_public/nsfwjscdn/nsfw_mobilenet2.224x224.h5

**Comment by onexuan** [comment]
it is possible to also publish 112x112 at the same time! 
Thank you for your great work, I will try to covert it other model to use it in android
