### ISSUE TITLE
Can I use this code to train different kind of images?

### ISSUE THREAD

**Issue by JanDintel** [GantMan/nsfw_model#31]
I'm quite new to machine learning, so please bear with me. I've got this idea to classify documents e.g. ID card, invoice, certificate. I was thinking to get a head start by reusing this model, but to train it on a different data set. Is it that 'simple' or am I underestimating the task?

**Comment by GantMan** [comment]
Yup, the transfer learning from this code would serve as a great tutorial for a different image recognition initiative.

I only wish my code was cleaner :D
