### ISSUE TITLE
download of the model TensorflowJS 224x224 is empty

### ISSUE THREAD

**Issue by LeandroSNunes** [GantMan/nsfw_model#40]
Hi guys
I am downloading the model TensorflowJS 224x224 Image Model and the folder is empty

![Screen Shot 2019-10-30 at 00 04 49](https://user-images.githubusercontent.com/656458/67825696-f138ec00-faa8-11e9-8180-c70695bbd398.png)

Where would be the best place for me to get the updated model?

**Comment by GantMan** [comment]
I need to fix this.  But for now:

The large 93% accurate model is here:
https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/model

The small 91% accurate model is here:
https://github.com/infinitered/nsfwjs/tree/master/example/nsfw_demo/public/quant_nsfw_mobilenet

**Comment by webciter** [comment]
im trying to use the 93 percent model but getting,  Error when checking : expected input_1 to have shape [null,299,299,3] but got array with shape [1,224,224,3]. When using this code

`const convertToTensor3d = async (img) => {
  // Decoded image in UInt8 Byte array
  const image = await jpeg.decode(img, true)

  const numChannels = 3
  const numPixels = image.width * image.height
  const values = new Int32Array(numPixels * numChannels)

  for (let i = 0; i < numPixels; i++)
    for (let c = 0; c < numChannels; ++c)
      values[i * numChannels + c] = image.data[i * 4 + c]

  return tf.tensor3d(values, [image.height, image.width, numChannels], 'int32')
}
`
