### ISSUE TITLE
Generate tagged saved_model.pd incl variables for Go (Mobilenet v2 224)

### ISSUE THREAD

**Issue by lastzero** [GantMan/nsfw_model#45]
We're working on a private cloud solution for personal photo management, see https://github.com/photoprism/photoprism

In order to enable uploading in our [demo](https://demo.photoprism.org/) again, I would like to add a NSFW filter based on TensorFlow. Your model looks promising, however I spent the whole day converting it to the right format and failed... either the output directory does not contain "variables.index" or the .pb can not be created because of too many / not enough layers, input parameters or output values. TF for Go strictly requires a tagged .pb file, we can not use the one that is offered for download.

This script worked for us to export Nasnet:

```
import keras
from keras.applications.nasnet import NASNetMobile
from keras.preprocessing import image
from keras.applications.xception import preprocess_input, decode_predictions
import numpy as np
import tensorflow as tf
from keras import backend as K
import json
import os
import sys

if not os.path.isfile("NASNet-mobile.h5"):
    os.system("curl -L -o NASNet-mobile.h5 http://modeldepot.io/assets/uploads/models/models/09a9e3fd-ebf0-46d4-bd5d-8be69d80cf44_NASNet-mobile.h5")

if len(sys.argv[1:]) > 0:
    modelName = sys.argv[1]
else:
    modelName = "nasnet-mobile"

sess = tf.Session()
K.set_session(sess)

model = NASNetMobile(weights="NASNet-mobile.h5")
img = image.load_img('gorge.jpg', target_size=(224,224)) #note the input size
img_arr = np.expand_dims(image.img_to_array(img), axis=0)
x = preprocess_input(img_arr)

preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

print('input: ', model.input)
print('output: ', model.output)

# Use TF to save the graph model instead of Keras save model to load it in Golang
builder = tf.saved_model.builder.SavedModelBuilder(modelName)
# Tag the model, required for Go
builder.add_meta_graph_and_variables(sess, ["photoprism"])
builder.save()
sess.close()
```

Simply replacing `NASNetMobile` with `MobileNetV2` +  `nsfw_mobilenet2.224x224.h5` didn't work (layer mismatch, I think this has ~107 and MobileNetV2 has about 105).

When using your code (here in this repository) to load the model, the error when saving is:

"FailedPreconditionError (see above for traceback): Attempting to use uninitialized value SGD_1/decay"

Docker is used as runtime environment - maybe we need other versions of TF or Keras?

```
#!/usr/bin/env sh

docker run -ti \
       -v ${PWD}:/nsfw \
       -w /nsfw \
       -u $(id -u):$(id -g) \
       gildasch/tensorflow-keras \
       python save.py
```

Our code for running inference (once we have a working model):
https://github.com/photoprism/photoprism/blob/develop/internal/photoprism/tensorflow.go

Would be amazing if somebody can give us a hint! 👍

**Comment by GantMan** [comment]
I'll try to look at this, this weekend.  No promises :D

**Comment by lastzero** [comment]
Thank you, we found a different model in the right format in the meantime... Probably based on yours somehow, not sure if it's better or worse.

**Comment by colindean** [comment]
If this is still a problem, please provide the version of nsfw_detector that you're using, your Python version, your Python platform, and a code example of how you're invoking nsfw_detector, and reopen the issue.
