### ISSUE TITLE
Publishing the graph

### ISSUE THREAD

**Issue by mycaule** [GantMan/nsfw_model#46]
Can you publish the graph as well for the `.pb` files ?
Compiling from the tensorflow sources can be hard depending on the environment.

**Comment by mycaule** [comment]
https://github.com/tensorflow/tensorflow/issues/18564

**Comment by mycaule** [comment]
There is this new feature that is very interesting 

https://blog.tensorflow.org/2020/01/run-tensorflow-savedmodel-in-nodejs-directly-without-conversion.html

No need to convert using `tfjs-converter` anymore!

**Comment by TechnikEmpire** [comment]
AFAIK this should be resolved now with the new TF2.1 trainer and published model @GantMan

**Comment by GantMan** [comment]
agreed https://github.com/GantMan/nsfw_model/releases
