### ISSUE TITLE
NSFW Detection

### ISSUE THREAD

**Issue by Kadantte** [GantMan/nsfw_model#5]
Is there a way to use something like this?
https://api.deepai.org/result/ad586df1-e781-409f-a3c5-ec14977c5b82

**Comment by bedapudi6788** [comment]
Hi @Kadantte , I think doing this won't be possible without manually drawing bounding boxes on the images.

**Comment by Kadantte** [comment]
Already have pictures with boxes but without JSON files I've them in text files. I am new at this stuff so is your training code could help with training a model for this purpose?

**Comment by bedapudi6788** [comment]
@Kadantte , to do this you will need to train a object recognition model. https://github.com/pierluigiferrari/ssd_keras might be a good start. On a side note, you will need a lot of images to train this type of model.

**Comment by Kadantte** [comment]
Thank's for help, anyway i E-mailed you again.

**Comment by GantMan** [comment]
@Kadantte - let us know if you ever make a dataset available.

[Especially if you add the bounding boxes to this large dataset](https://github.com/GantMan/nsfw_model/files/2931759/NSFW_March_2019.7z.torrent.zip)

For now I'll close this issue.
