### ISSUE TITLE
Use FFMPEG to split Big Buck Bunny's frames out every Nth frame and add to the training set

### ISSUE THREAD

**Issue by TechnikEmpire** [GantMan/nsfw_model#50]
If you ask the classifier to look at the Big Buck Bunny movie, it's basically seeing porn everywhere. It follows that the adding this stuff to one of the safe categories may help the model further differentiate between NSFW and neutral. [Here's how to do it](https://superuser.com/questions/391257/extracting-one-of-every-10-frames-in-a-video-using-vlc-or-ffmpeg).

**Comment by GantMan** [comment]
Which model are you using?  I fear I might have an older version linked.

**Comment by TechnikEmpire** [comment]
I pulled the tf mobilenet v2 model and then converted it to run on Intel's DLTD (mkl-dnn, part of open CV project now).

**Comment by TechnikEmpire** [comment]
@GantMan For greater clarity, big buck bunny is real problematic on any model like this. I've been training many variants for a long time and it's always a pain, especially whenever there are frames showing his ears if you know what I'm sayin.

**Comment by TechnikEmpire** [comment]
This doesn't seem to be as much of an issue anymore so I'm going to close this out.
