### ISSUE TITLE
 ValueError: Unknown layer: KerasLayer

### ISSUE THREAD

**Issue by hasan-haider** [GantMan/nsfw_model#61]
I'm doing in google colab and after loading model i got an error.
Will you explain me what should i do?
`ValueError                                Traceback (most recent call last)
<ipython-input-28-f67ed1cccb9b> in <module>()
      1 from nsfw_detector import predict
----> 2 model = predict.load_model('./saved_model.h5')
      3 
      4 # Predict single image
      5 predict.classify(model, 'nsfw.jpg')

9 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/utils/generic_utils.py in class_and_config_for_serialized_keras_object(config, module_objects, custom_objects, printable_module_name)
    319   cls = get_registered_object(class_name, custom_objects, module_objects)
    320   if cls is None:
--> 321     raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
    322 
    323   cls_config = config['config']

ValueError: Unknown layer: KerasLayer`

**Comment by Cfish808** [comment]
I meet the same error, and have you solve it ?

**Comment by hasan-haider** [comment]
No.

**Comment by Vivek8430** [comment]
Same issue occured @GantMan can you help in this?

**Comment by PravinVedurla** [comment]
For future readers, It's a problem with tf-hub. Try changing your version to tf 2.0 or There's a fix mentioned here - [https://github.com/tensorflow/tensorflow/issues/26835#issuecomment-485534826](URL)

**Comment by Cfish808** [comment]
I have solved it:
model = tf.keras.models.load_model(model_path, custom_objects={'KerasLayer': hub.KerasLayer})

**Comment by hasan-haider** [comment]
> I have solved it:
> model = tf.keras.models.load_model(model_path, custom_objects={'KerasLayer': hub.KerasLayer})

import tensorflow as tf
import tensorflow_hub as hub

It worked. Thanks
