### ISSUE TITLE
How do I use the model in TensorFlow JS?

### ISSUE THREAD

**Issue by navendu-pottekkat** [GantMan/nsfw_model#65]
Can anyone share the code of how I can use this model in tfjs?

const model = await tf.loadLayersModel('models/model.json')

I downloaded the model zip and loaded it as follows. How can I then use this in javascript code to access the model and classify images

**Comment by GantMan** [comment]
Best way to use this in TFJS is to use NSFWJS which is wrapped around this
https://github.com/infinitered/nsfwjs

**Comment by navendu-pottekkat** [comment]
Thanks I will check it out!
