### ISSUE TITLE
Can't load the model

### ISSUE THREAD

**Issue by Christoph-Schuhmann** [GantMan/nsfw_model#69]
For a reason I don't understand I always get this error. What can I do to fix it?

![grafik](https://user-images.githubusercontent.com/47485939/88701702-abc64f80-d10a-11ea-92d7-15170078c065.png)

OSError                                   Traceback (most recent call last)

<ipython-input-14-7e117d10dbb7> in <module>()
      6 
      7 from nsfw_detector import predict
----> 8 model = predict.load_model('nsfw_mobilenet2.224x224.h5')
      9 
     10 # Predict single image

4 frames

/usr/local/lib/python3.6/dist-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    171         if swmr and swmr_support:
    172             flags |= h5f.ACC_SWMR_READ
--> 173         fid = h5f.open(name, flags, fapl=fapl)
    174     elif mode == 'r+':
    175         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (truncated file: eof = 9437184, sblock->base_addr = 0, stored_eof = 10956472)

**Comment by GantMan** [comment]
Glad you got it!
