### ISSUE TITLE
Error with latest version of Tensorflow (2.3.0)

### ISSUE THREAD

**Issue by NotCompsky** [GantMan/nsfw_model#70]
This project works fine with Tensorflow 2.1.0, but with Tensorflow 2.3.0 I got the following error for every `predict.classify` call:

`ValueError: Negative dimension size caused by subtracting 8 from 5 for '{{node model_1/average_pooling2d_10/AvgPool}} = AvgPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 8, 8, 1], padding="VALID", strides=[1, 8, 8, 1]](model_1/mixed10/concat)' with input shapes: [?,5,5,2048]`

Googling around, I only get hits for this error from 2017-2019, such as [this](https://stackoverflow.com/questions/41651628/negative-dimension-size-caused-by-subtracting-3-from-1-for-conv2d) which suggests the solution is to change the default ordering of the images in the Keras backend.

This was fixed with a simple downgrade of Tensorflow to version 2.1.0. I did not try any intermediate versions.

Has anyone else had this issue?

**Comment by colindean** [comment]
If this is still a problem, please provide the version of nsfw_detector that you're using, your Python version, your Python platform, and a code example of how you're invoking nsfw_detector, and reopen the issue.
