### ISSUE TITLE
web model not working in the latest release

### ISSUE THREAD

**Issue by navendu-pottekkat** [GantMan/nsfw_model#75]
@GantMan I tried the latest web model from the release titled [Updated Models!](https://github.com/GantMan/nsfw_model/releases/tag/1.2.0) and it does not seem to work with the nsfwjs library.

We are currently using [this model](https://github.com/infinitered/nsfwjs/blob/master/example/nsfw_demo/public/quant_nsfw_mobilenet/) shown in the nsfwjs repo and would like to update it to the latest model. Normally, changing the model.json file and shards should work right? But it is not working in [our project](https://github.com/nsfw-filter/nsfw-filter/issues/80).

Does the latest release in this repo (the web model) work with nsfwjs library. How can we update the model we use currently easily?

**Comment by navendu-pottekkat** [comment]
I do not think this is an issue with the model itself but maybe it not being read by the function from the nsfwjs library?

**Comment by colindean** [comment]
If this is still a problem, please provide the version of nsfw_detector that you're using, your Python version, your Python platform, and a code example of how you're invoking nsfw_detector, and reopen the issue.
