### ISSUE TITLE
Use in movie frames

### ISSUE THREAD

**Issue by xcbtrader** [GantMan/nsfw_model#76]
Hello.
I'm use python OpenCv to extrac frames for movie.

I don't know how to do a predict on the variable once the frame is recovered.

The only way I have achieved it is by saving the frame as .jpg, opening the image and then analyzing it.
Any ideas?

Example code:
`import cv2

file = input('Video name: ? ')
cap = cv2.VideoCapture(file)

while True:
	ret, frame = cap.read()`

**Comment by colindean** [comment]
If this is still a problem, please provide the version of nsfw_detector that you're using, your Python version, your Python platform, and a code example of how you're invoking nsfw_detector, and reopen the issue.

Look at [`nsfw_detector.predict.classify_nd()`](https://github.com/GantMan/nsfw_model/blob/80bc87dfe44f900fb74ca71e773c8ed66c86f231/nsfw_detector/predict.py#L67-L81) to see if it does what you want. You'll need call `load_model()` yourself and also prepare the image data like how [`load_images()`](https://github.com/GantMan/nsfw_model/blob/80bc87dfe44f900fb74ca71e773c8ed66c86f231/nsfw_detector/predict.py#L38-L50) does.
