### ISSUE TITLE
Error in make_nsfw_model_lib.py

### ISSUE THREAD

**Issue by mojindri** [GantMan/nsfw_model#78]
Hi,
i'm tryiung to run the nsfw_model, but sadly i face this error 
![image](https://user-images.githubusercontent.com/2129026/95690328-305b4100-0c17-11eb-9178-981f300d5324.png)

**Comment by chinalu** [comment]
Which version of Python?

**Comment by colindean** [comment]
If this is still a problem, please provide the version of nsfw_detector that you're using, your Python version, your Python platform, and a code example of how you're invoking nsfw_detector, and reopen the issue. This screenshot is too difficult to determine these.
