### ISSUE TITLE
model.json version model is not as good as .h5 version

### ISSUE THREAD

**Issue by qiankunxienb** [GantMan/nsfw_model#83]
For example, https://s3.amazonaws.com/ir_public/nsfwjscdn/nsfw_mobilenet2.224x224.h5 is more accurate than https://github.com/GantMan/nsfw_model/releases/download/1.2.0/mobilenet_v2_140_224.1.zip.

What is the key difference?

**Comment by GantMan** [comment]
The one on s3 was created using TF1.0 by me, and the second one was by @TechnikEmpire who's been helping improve the model.

**Comment by TechnikEmpire** [comment]
I would ask for evidence to back up the accuracy claims but, yesterday I re-trained a model and tf said it was 96% accurate... then I tested it in a brand new group of images never seen before in train or validation and "accuracy" was not a word I would even use to describe anything about it. Puzzling.

**Comment by GantMan** [comment]
Agreed.  We need data.

**Comment by qiankunxienb** [comment]
for example, please see the images below:
![0OUtSc_G_004dBV7E00](https://user-images.githubusercontent.com/71627005/104537758-8811aa00-5655-11eb-83f3-c7a3fe65119c.jpeg)

the results of mode.json vs h5 are like below:

![image](https://user-images.githubusercontent.com/71627005/104537735-80520580-5655-11eb-9927-4c23ef1ccb9e.png)

mode.json version model says it is more like a porn image than h5 version model.

**Comment by qiankunxienb** [comment]
However, https://nsfwjs.com/  always do the right job.

![image](https://user-images.githubusercontent.com/71627005/104540982-982c8800-565b-11eb-800e-7c73b92bfe77.png)

How does this site do a better job? Did the site train the mode by itself or use the same mode as you?

**Comment by GantMan** [comment]
The site 93% model I believe is one release version old.

The 90% accuracy was from the TF 1.0 training session.

Can you look through release history and see which model works best for you and we'll try to update?

**Comment by TechnikEmpire** [comment]
> However, https://nsfwjs.com/ always do the right job.

I'd just like to point out that, it's not doing "the right job", it's calling a screen grab of a police interaction a "drawing".

**Comment by sickfuck666** [comment]
Hi guys!
Just tested now - site works better than all model that i can download.
Can you please upload site's model somewhere?

**Comment by colindean** [comment]
I believe this is resolved. Please reopen if you have further questions or discussion.
