### ISSUE TITLE
Not able to download the model - nsfw.299x299.h5

### ISSUE THREAD

**Issue by Navaneethsen** [GantMan/nsfw_model#9]
Hi,

When I try to download the model **nsfw.299x299.h5** from the URL [s3.amazonaws.com/nsfwdetector/nsfw.299x299.h5](https://s3.amazonaws.com/nsfwdetector/nsfw.299x299.h5), I get the below response. 

![image](https://user-images.githubusercontent.com/929451/53721374-c50e9200-3e6b-11e9-8f6e-672466a57371.png)

How can I get this model?

**Comment by GantMan** [comment]
Please try again now.  Amazon was having permission issues.

**Comment by Navaneethsen** [comment]
Thanks.

**Comment by jrusakov** [comment]
Hi, help please, I can't download the model nsfw.299x299.h5

**Comment by adamalexander** [comment]
@jrusakov any luck since?

**Comment by GantMan** [comment]
I had to move the file, we were hitting $40 a month in S3 pricing.

I can give you the new link, but when it gets expensive, I'll probably move it again.

Sounds good?

**Comment by adamalexander** [comment]
@GantMan yeah that'll be super! Thanks how can I get it?

**Comment by GantMan** [comment]
I believe this is the last h5
https://s3.amazonaws.com/ir_public/ai/nsfw_models/february_2019_nsfw.299x299.h5
