### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by brokoder** [GantMan/nsfw_model#95]
I reached this project from nsfwjs.com because from what i understood was that site uses images in [nsfw_data_scraper](https://github.com/alex000kim/nsfw_data_scraper) to train the data. i just downloaded an image in the porn catagory and tested it in https://nsfwjs.com/ and to my surprise **it listed as a drawing**. I don't know much about ML but is it suppose to be like that?

**Comment by GantMan** [comment]
Which model did you use?   Yes there are always mistakes when the model is 93% accurate.   

If you'd like, you can submit the image to me to be added to the training dataset.  Not on GitHub obviously.
